pipeline {
    agent any

    environment {
        SERVER_IP = "172.31.27.240"
        DEPLOY_DIR = "/var/www/html"
        SSH_KEY = "/home/ubuntu/.ssh/id_rsa"
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/devjthwa/New-folder--2--main.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('my-react-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('my-react-app') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy to Apache Server') {
            steps {
                sh '''
                echo "Cleaning Apache folder..."
                ssh -i $SSH_KEY -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "sudo rm -rf $DEPLOY_DIR/*"

                echo "Copying build files..."
                scp -i $SSH_KEY -o StrictHostKeyChecking=no -r my-react-app/dist/* ubuntu@$SERVER_IP:$DEPLOY_DIR
                '''
            }
        }

    }
}