pipeline {
    agent any

    environment {
        SERVER_IP = "172.31.27.240"
        DEPLOY_DIR = "/var/www/html"
        SSH_KEY = "/var/lib/jenkins/.ssh/id_rsa"
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/devjthwa/New-folder--2--main.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('my-react-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('my-react-app') {
                    sh 'npm run build'
                }
            }
        }

        stage('Verify Build Output') {
            steps {
                sh '''
                echo "Checking dist folder..."
                ls -R my-react-app/dist
                '''
            }
        }

        stage('Deploy to Apache Server') {
            steps {
                sh '''
                echo "Cleaning old files on server..."
                ssh -i $SSH_KEY -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "
                    sudo rm -rf /var/www/html/*"

                echo "Deploying React build..."
                scp -i $SSH_KEY -o StrictHostKeyChecking=no -r my-react-app/dist/. ubuntu@$SERVER_IP:/var/www/html/

                echo "Verifying deployment..."
                ssh -i $SSH_KEY ubuntu@$SERVER_IP "ls -R $DEPLOY_DIR"
                '''
            }
        }
    }

    post {
        success {
            echo "Deployment SUCCESS 🚀"
        }
        failure {
            echo "Deployment FAILED ❌ Check logs"
        }
    }
}